[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {workspace = true}
serde_json = {workspace = true}
tokio = { workspace = true }
reqwest = { workspace = true }

axum = "0.7"
sqlx = {version = "0.7", features = ["mysql", "runtime-tokio"]}
