name: Rust

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt
            - name: Run cargo fmt
              run: |
                  cargo fmt --all -- --check
    test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: movie_db
                ports:
                    - 3306:3306
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - name: Install sqlx-cli
              run: |
                  cargo install sqlx-cli
            - name: Migrate database
              env:
                  DATABASE_URL: ${{ vars.DATABASE_URL }}
              run: |
                  cd server
                  sqlx database create
                  sqlx migrate run
            - name: Run cargo test & clippy
              env:
                  API_KEY: ${{ secrets.TMDB_API_KEY }}
              run: |
                  cargo test &
                  cargo clippy --all-targets --all-features -- -D warnings &
                  wait